# encoding utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

Style.create(:name => 'Ale')
Style.create(:name => 'Lager')
Style.create(:name => 'American Amber or Red Ale')
Style.create(:name => 'American Barleywine')
Style.create(:name => 'American Blonde Ale')
Style.create(:name => 'American Brown Ale')
Style.create(:name => 'American Dark Wheat Ale')
Style.create(:name => 'American Double IPA (Imperial IPA)')
Style.create(:name => 'American Double Stout (Imperial Stout)')
Style.create(:name => 'American IPA')
Style.create(:name => 'American Pale Ale')
Style.create(:name => 'American Pale Wheat Ale')
Style.create(:name => 'American Porter')
Style.create(:name => 'American Stout')
Style.create(:name => 'American Strong Ale')
Style.create(:name => 'American Wild Ale')
Style.create(:name => 'Black & Tan')
Style.create(:name => 'Black IPA (Cascadian Dark Ale)')
Style.create(:name => 'Chili Beer')
Style.create(:name => 'Cream Ale')
Style.create(:name => 'Pumpkin Ale')
Style.create(:name => 'Rye Beer')
Style.create(:name => 'Wheatwine')
Style.create(:name => 'Belgian Dark Ale')
Style.create(:name => 'Belgian IPA')
Style.create(:name => 'Belgian Pale Ale')
Style.create(:name => 'Belgian Strong Dark Ale')
Style.create(:name => 'Belgian Strong Pale Ale')
Style.create(:name => 'Bière de Champagne (Bière Brut)')
Style.create(:name => 'Bière de Garde')
Style.create(:name => 'Dubbel')
Style.create(:name => 'Faro')
Style.create(:name => 'Oud Bruin (Flanders Brown Ale)')
Style.create(:name => 'Flanders Red Ale')
Style.create(:name => 'Gueuze')
Style.create(:name => 'Fruit Lambic')
Style.create(:name => 'Unblended Lambic')
Style.create(:name => 'Quadrupel')
Style.create(:name => 'Saison (Farmhouse Ale)')
Style.create(:name => 'Tripel')
Style.create(:name => 'Witbier')
Style.create(:name => 'Baltic Porter')
Style.create(:name => 'Braggot')
Style.create(:name => 'English Barleywine')
Style.create(:name => 'English Bitter')
Style.create(:name => 'English Brown Ale')
Style.create(:name => 'English Dark Mild Ale')
Style.create(:name => 'English IPA')
Style.create(:name => 'English Pale Ale')
Style.create(:name => 'English Pale Mild Ale')
Style.create(:name => 'English Porter')
Style.create(:name => 'English Stout')
Style.create(:name => 'English Strong Ale')
Style.create(:name => 'Extra Special or Strong Bitter (ESB)')
Style.create(:name => 'Foreign Stout')
Style.create(:name => 'Milk Stout (Sweet Stout)')
Style.create(:name => 'Oatmeal Stout')
Style.create(:name => 'Old Ale')
Style.create(:name => 'Russian Imperial Stout')
Style.create(:name => 'Winter Warmer')
Style.create(:name => 'Sahti')
Style.create(:name => 'Altbier')
Style.create(:name => 'Berliner Weissbier')
Style.create(:name => 'Dunkelweizen')
Style.create(:name => 'Gose')
Style.create(:name => 'Hefeweizen')
Style.create(:name => 'Kristalweizen')
Style.create(:name => 'Kölsch')
Style.create(:name => 'Roggenbier')
Style.create(:name => 'Weizenbock')
Style.create(:name => 'Irish Dry Stout')
Style.create(:name => 'Irish Red Ale')
Style.create(:name => 'Kvass')
Style.create(:name => 'Scotch Ale (Wee Heavy)')
Style.create(:name => 'Scottish Ale')
Style.create(:name => 'Scottish Gruit (Ancient Herbed Ale)')
Style.create(:name => 'American Adjunct Lager')
Style.create(:name => 'American Amber or Red Lager')
Style.create(:name => 'American Double Pilsner (Imperial Pilsner)')
Style.create(:name => 'American Malt Liquor')
Style.create(:name => 'American Pale Lager')
Style.create(:name => 'California Common (Steam Beer)')
Style.create(:name => 'Light Lager')
Style.create(:name => 'Low Alcohol Beer')
Style.create(:name => 'Czech Pilsener')
Style.create(:name => 'European Dark Lager')
Style.create(:name => 'European Pale Lager')
Style.create(:name => 'European Strong Lager')
Style.create(:name => 'Bock')
Style.create(:name => 'Doppelbock')
Style.create(:name => 'Dortmunder')
Style.create(:name => 'Eisbock')
Style.create(:name => 'German Pilsener')
Style.create(:name => 'Kellerbier (Zwickelbier)')
Style.create(:name => 'Maibock (Helles Bock)')
Style.create(:name => 'Munich Dunkel Lager')
Style.create(:name => 'Munich Helles Lager')
Style.create(:name => 'Märzen (Oktoberfest)')
Style.create(:name => 'Rauchbier')
Style.create(:name => 'Schwarzbier')
Style.create(:name => 'Vienna Lager')
Style.create(:name => 'Happoshu')
Style.create(:name => 'Japanese Rice Lager')
Style.create(:name => 'Fruit or Vegetable Beer')
Style.create(:name => 'Herbed or Spiced Beer')
Style.create(:name => 'Smoked Beer')
Style.create(:name => 'Stout or Porter')
Style.create(:name => 'Pale Ale')
Style.create(:name => 'Belgian or French Ale')
Style.create(:name => 'American Lager')
Style.create(:name => 'Pilsner')
Style.create(:name => 'German Lager')
Style.create(:name => 'German Ale')
Style.create(:name => 'Japanese Lager')
Style.create(:name => 'Weissbier')
Style.create(:name => 'Strong Pale Ale')

brewery = Brewery.create(:name => 'Dogfish Head Craft Brewery', :website => 'http://www.dogfish.com')

brewery.beers.create(:name => "DFH Ale", :abv => 9.5, :style => Style.find_by_name('American Double IPA (Imperial IPA)'))
brewery.beers.create(:name => "Goser The Gosarian", :abv => 4.5, :style => Style.find_by_name('Gose'))
brewery.beers.create(:name => "Grau Dunkel", :abv => 5.2, :style => Style.find_by_name('Dunkelweizen'))
brewery.beers.create(:name => "Lawnmower Light", :abv => 4.0, :style => Style.find_by_name('American Pale Ale'))
brewery.beers.create(:name => "Le Kabouter De Guerre", :abv => 8.9, :style => Style.find_by_name('Belgian IPA'))
brewery.beers.create(:name => "Liquor De Malt", :abv => 7.0, :style => Style.find_by_name('American Malt Liquor'))
brewery.beers.create(:name => "Odd-ummm", :abv => 7.5, :style => Style.find_by_name('Herbed or Spiced Beer'))
brewery.beers.create(:name => "Fort", :abv => 18.0, :style => Style.find_by_name('Fruit or Vegetable Beer'))
brewery.beers.create(:name => "Immort Ale", :abv => 11.0, :style => Style.find_by_name('American Strong Ale'))
brewery.beers.create(:name => "Arctic Cloudberry Imperial Wheat", :abv => 8.5, :style => Style.find_by_name('Wheatwine'))
brewery.beers.create(:name => "Arms Akimbo", :abv => 6.5, :style => Style.find_by_name('American Porter'))
brewery.beers.create(:name => "Au Courant", :abv => 7.0, :style => Style.find_by_name('Belgian Strong Pale Ale'))
brewery.beers.create(:name => "Ballot Brown Ale", :abv => 5.0, :style => Style.find_by_name('American Brown Ale'))
brewery.beers.create(:name => "Baltic De Belgian", :abv => 5.0, :style => Style.find_by_name('Belgian Dark Ale'))
brewery.beers.create(:name => "Baltic Porter", :abv => 8.0, :style => Style.find_by_name('Baltic Porter'))
brewery.beers.create(:name => "120 Minute IPA", :abv => 18.0, :style => Style.find_by_name('American Double IPA (Imperial IPA)'))
brewery.beers.create(:name => "75 Minute IPA", :abv => 7.5, :style => Style.find_by_name('American IPA'))
brewery.beers.create(:name => "ApriHop", :abv => 7.0, :style => Style.find_by_name('American IPA'))
brewery.beers.create(:name => "Black & Blue", :abv => 10.0, :style => Style.find_by_name('Fruit or Vegetable Beer'))
brewery.beers.create(:name => "Burton Baton", :abv => 10.0, :style => Style.find_by_name('American Double IPA (Imperial IPA)'))
brewery.beers.create(:name => "Chateau Jiahu", :abv => 8.0, :style => Style.find_by_name('Herbed or Spiced Beer'))
brewery.beers.create(:name => "Chicory Stout", :abv => 5.2, :style => Style.find_by_name('American Stout'))
brewery.beers.create(:name => "Festina Pêche", :abv => 4.5, :style => Style.find_by_name('Berliner Weissbier'))
brewery.beers.create(:name => "Indian Brown Ale", :abv => 7.2, :style => Style.find_by_name('American Brown Ale'))
brewery.beers.create(:name => "My Antonia", :abv => 7.5, :style => Style.find_by_name('American Double Pilsner (Imperial Pilsner)'))
brewery.beers.create(:name => "Olde School Barleywine", :abv => 15.04, :style => Style.find_by_name('American Barleywine'))
brewery.beers.create(:name => "ESB", :abv => 5.0, :style => Style.find_by_name('Extra Special or Strong Bitter (ESB)'))
brewery.beers.create(:name => "60 Minute IPA", :abv => 6.0, :style => Style.find_by_name('American IPA'))
brewery.beers.create(:name => "90 Minute IPA", :abv => 9.0, :style => Style.find_by_name('American Double IPA (Imperial IPA)'))
brewery.beers.create(:name => "Midas Touch Golden Elixir", :abv => 9.0, :style => Style.find_by_name('Herbed or Spiced Beer'))
brewery.beers.create(:name => "Beanie Bock", :abv => 9.0, :style => Style.find_by_name('Weizenbock'))
brewery.beers.create(:name => "Blood Orange Hefeweizen", :abv => 4.5, :style => Style.find_by_name('Hefeweizen'))
brewery.beers.create(:name => "Daily Wry", :abv => 4.3, :style => Style.find_by_name('English Porter'))
brewery.beers.create(:name => "Dan's Saison", :abv => 5.0, :style => Style.find_by_name('Saison (Farmhouse Ale)'))
brewery.beers.create(:name => "Double R Ale", :abv => 9.0, :style => Style.find_by_name('Belgian Strong Dark Ale'))
brewery.beers.create(:name => "Espresso Bock", :abv => 7.5, :style => Style.find_by_name('Bock'))
brewery.beers.create(:name => "FedExtra Mild", :abv => 6.2, :style => Style.find_by_name('American IPA'))
brewery.beers.create(:name => "Festina Lente", :abv => 7.0, :style => Style.find_by_name('Fruit Lambic'))
brewery.beers.create(:name => "Flucky Fest", :abv => 6.0, :style => Style.find_by_name('Fruit or Vegetable Beer'))
brewery.beers.create(:name => "Golden Era", :abv => 9.0, :style => Style.find_by_name('American Double Pilsner (Imperial Pilsner)'))
brewery.beers.create(:name => "Hefe'rye'zen", :abv => 5.0, :style => Style.find_by_name('Rye Beer'))
brewery.beers.create(:name => "Hommel Bier", :abv => 5.0, :style => Style.find_by_name('Belgian Pale Ale'))
brewery.beers.create(:name => "Immoak Ale", :abv => 5.0, :style => Style.find_by_name('American Strong Ale'))
brewery.beers.create(:name => "Steampunk Porter", :abv => 6.5, :style => Style.find_by_name('American Porter'))
brewery.beers.create(:name => "Saison Du BUFF", :abv => 6.8, :style => Style.find_by_name('Saison (Farmhouse Ale)'))
brewery.beers.create(:name => "Pangaea", :abv => 7.0, :style => Style.find_by_name('Belgian Strong Pale Ale'))
brewery.beers.create(:name => "Raison D'etre", :abv => 8.0, :style => Style.find_by_name('Belgian Strong Dark Ale'))
brewery.beers.create(:name => "Squall IPA", :abv => 9.0, :style => Style.find_by_name('American Double IPA (Imperial IPA)'))
brewery.beers.create(:name => "Punkin Ale", :abv => 7.0, :style => Style.find_by_name('Pumpkin Ale'))
brewery.beers.create(:name => "Bitches Brew", :abv => 9.0, :style => Style.find_by_name('Russian Imperial Stout'))
brewery.beers.create(:name => "Namaste", :abv => 5.0, :style => Style.find_by_name('Witbier'))
brewery.beers.create(:name => "Altar Boy", :abv => 7.0, :style => Style.find_by_name('Dubbel'))
brewery.beers.create(:name => "Bam Bam Baji", :abv => 4.5, :style => Style.find_by_name('English Bitter'))
brewery.beers.create(:name => "Black Thai", :abv => 9.0, :style => Style.find_by_name('Russian Imperial Stout'))
brewery.beers.create(:name => "Chicha", :abv => 6.2, :style => Style.find_by_name('Fruit or Vegetable Beer'))
brewery.beers.create(:name => "Red & White", :abv => 10.0, :style => Style.find_by_name('Witbier'))
brewery.beers.create(:name => "Sah'tea", :abv => 9.0, :style => Style.find_by_name('Sahti'))
brewery.beers.create(:name => "World Wide Stout", :abv => 18.0, :style => Style.find_by_name('American Double Stout (Imperial Stout)'))
brewery.beers.create(:name => "Shark Beer", :abv => 4.5, :style => Style.find_by_name('Kölsch'))
brewery.beers.create(:name => "Shelter Pale Ale", :abv => 5.0, :style => Style.find_by_name('American Pale Ale'))
brewery.beers.create(:name => "Palo Santo Marron", :abv => 12.0, :style => Style.find_by_name('American Brown Ale'))
brewery.beers.create(:name => "Stop The Spill ESB", :abv => 6.0, :style => Style.find_by_name('Extra Special or Strong Bitter (ESB)'))
brewery.beers.create(:name => "Up Up Down Down Left Right Left Right BA Select", :abv => 8.0, :style => Style.find_by_name('American Brown Ale'))
brewery.beers.create(:name => "Pale India Ale", :abv => 6.0, :style => Style.find_by_name('Bière de Garde'))
brewery.beers.create(:name => "Portamarillo", :abv => 7.0, :style => Style.find_by_name('American Porter'))
brewery.beers.create(:name => "Theobroma", :abv => 9.0, :style => Style.find_by_name('Chili Beer'))
brewery.beers.create(:name => "Quartier Rouge", :abv => 9.4, :style => Style.find_by_name('American Amber or Red Ale'))
brewery.beers.create(:name => "Voodoo Down", :abv => 9.0, :style => Style.find_by_name('American Double Stout (Imperial Stout)'))
brewery.beers.create(:name => "Raison D'extra", :abv => 18.0, :style => Style.find_by_name('Belgian Strong Dark Ale'))
brewery.beers.create(:name => "Ryehoboth", :abv => 5.5, :style => Style.find_by_name('Rye Beer'))
brewery.beers.create(:name => "Wet Hop American Summer", :abv => 5.0, :style => Style.find_by_name('American Pale Lager'))
brewery.beers.create(:name => "Whassthat Black IPA", :abv => 8.5, :style => Style.find_by_name('Black IPA (Cascadian Dark Ale)'))
brewery.beers.create(:name => "Wrath Of Pecant!", :abv => 6.0, :style => Style.find_by_name('American Brown Ale'))
brewery.beers.create(:name => "Zeno", :abv => 5.2, :style => Style.find_by_name('Saison (Farmhouse Ale)'))
brewery.beers.create(:name => "75 Minute (with Maple)", :abv => 7.5, :style => Style.find_by_name('American Double IPA (Imperial IPA)'))
brewery.beers.create(:name => "Zwaanend'ale", :abv => 8.0, :style => Style.find_by_name('Bock'))
brewery.beers.create(:name => "Johnny Rawton", :abv => 5.0, :style => Style.find_by_name('American Pale Lager'))
brewery.beers.create(:name => "Mushroom Stout", :abv => 5.0, :style => Style.find_by_name('Fruit or Vegetable Beer'))
brewery.beers.create(:name => "Oyster Stout", :abv => 5.0, :style => Style.find_by_name('English Stout'))
brewery.beers.create(:name => "Piston Honda", :abv => 4.5, :style => Style.find_by_name('American Pale Lager'))
brewery.beers.create(:name => "Prescription Pils", :abv => 9.0, :style => Style.find_by_name('American Double Pilsner (Imperial Pilsner)'))
brewery.beers.create(:name => "Snowblower Ale", :abv => 7.0, :style => Style.find_by_name('Belgian Strong Pale Ale'))
brewery.beers.create(:name => "Spruce Willis", :abv => 5.0, :style => Style.find_by_name('Herbed or Spiced Beer'))
brewery.beers.create(:name => "Surrender Monkey", :abv => 4.1, :style => Style.find_by_name('Scottish Gruit (Ancient Herbed Ale)'))
brewery.beers.create(:name => "T'ej", :abv => 10.0, :style => Style.find_by_name('Herbed or Spiced Beer'))
brewery.beers.create(:name => "Verdi Verdi Good", :abv => 5.5, :style => Style.find_by_name('Dortmunder'))
brewery.beers.create(:name => "WeedWacker Wit", :abv => 4.5, :style => Style.find_by_name('Witbier'))
brewery.beers.create(:name => "Woody", :abv => 11.0, :style => Style.find_by_name('American Double IPA (Imperial IPA)'))